### ISSUE TITLE
Review dao.py

### ISSUE THREAD

**Issue by RituKapur-Developer** [RituKapur-Developer/GuestFacFilter#4]
Please review dao.py
Especially, the below code snippet:
`def create_one_time_tables():
    conn = est_connection()
    cursor = conn.cursor()
    query0 = "create table recruit.skillExp(skillId Int, skillName varchar(100), minExp Double, maxExp Double)"
    cursor.execute(query0)
    conn.commit()
    '''
    query1 = 'create table recruit.candidate_skill_exp(recordID Int, ApplicantID Int, Skill Varchar(100), Experience Double);'
    cursor.execute(query1)
    conn.commit()
    print("Skill Table Created. Now inserting records")
    conn.commit()
    '''
    conn.close()
    return`
[Session 3 SDM.pdf](https://github.com/RituKapur-Developer/GuestFacFilter/files/10307916/Session.3.SDM.pdf)

**Comment by etgroupcine** [comment]
Everything is good. I reviewed it!

**Comment by RituKapur-Developer** [comment]
All good, I am closing this issue.
